name: finpong_plus
description: Finpong Plus Widget
version: 0.1.3
homepage: https://guide.finpong.com/

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  flutter_inappwebview: ^5.8.0
  webview_flutter: ^4.4.1
  url_launcher: ^6.1.11

  dio: ^5.0.3
  freezed: ^2.3.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  fluttertoast: ^8.1.1
  device_info_plus: ^8.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  json_serializable: ^6.7.0

flutter:
  plugin:
    platforms:
      android:
        package: com.finpong.finpong_plus
        pluginClass: FinpongPlusPlugin
      ios:
        pluginClass: FinpongPlusPlugin
